### ISSUE TITLE
little error

### ISSUE THREAD

**Issue by Amir-Alipour** [bvaughn/planner#1] opened 2021-12-30 09:50 UTC
Hi bro, that's great ❤
i try to  added new team metadata, when i changed the "name", i saw a error

![Screenshot (68)](https://user-images.githubusercontent.com/73488911/147740325-b8b94b2c-9752-4791-899f-21e433602b9c.png)

i think it can be fix with "?." operator

src/utils/color.js => line 2
```js
export function hexToRgb(hex) {
  if (hex?.length === 4) {
```

**Comment by bvaughn** [comment] 2021-12-30 14:48
Ah, right. The issue is that I only put in a few hard-coded colors to cycle through. I'll fix it with the way I'm cycling colors.

**Comment by bvaughn** [comment] 2021-12-30 14:49
Fixed via aac420f0173d8337d3c1ae2a7505d1a072b9f6fa

**Closed by bvaughn** 2021-12-30 14:49 UTC
